Repository viivue/easy-popup, pull requests merged in 2024-10, with the labels that each got.

#35 hasMobileLayout: showing 2 close buttons on desktop
  src/css/layout-mobile.scss
  src/layouts.js
Labels: bug

#36 fix(outerClass): trim string to avoid adding empty class
  src/html.js
Labels: bug

#37 Remove layout shift on popup open
  dev/index.html
  dev/md/faq.md
  dev/md/options.md
  dev/script.js
  src/_index.js
  src/configs.js
  src/helpers.js
  src/utils/getScrollbarWidth.js
  src/utils/isMobile.js
Labels: enhancement

#39 Add dev mode
  dev/md/methods.md
  package-lock.json
  src/_index.js
  src/configs.js
  src/pia-easy-popup.js
Labels: enhancement, good first issue

#38 Staging v1.2.0
  README.md
  dev/index.html
  dev/md/begin.md
  dev/md/faq.md
  dev/md/methods.md
  dev/md/options.md
  dev/script.js
  dist/easy-popup.css
  dist/easy-popup.js
  dist/easy-popup.min.css
  dist/easy-popup.min.js
  dist/easy-popup.module.js
  package-lock.json
  package.json
  src/_index.js
  src/_style.scss
  src/configs.js
  src/helpers.js
  src/html.js
  src/pia-easy-popup.js
  src/utils/getScrollbarWidth.js
  src/utils/isMobile.js
Labels: enhancement, good first issue
